name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew build

  http-tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Setup Gradle (caching, summaries)
        uses: gradle/actions/setup-gradle@v4

      - name: Start app
        run: |
          nohup ./gradlew bootRun --no-daemon > app.log 2>&1 &
          echo "APP_PID=$!" >> $GITHUB_ENV

      - name: Wait for app to be ready
        run: |
          for i in {1..60}; do
            if curl -sf http://127.0.0.1:8080/ping >/dev/null; then
              echo "up"; break
            elif curl -sf http://127.0.0.1:8080/actuator/health >/dev/null; then
              echo "up"; break
            fi
            sleep 1
          done

      - name: Download ijhttp (HTTP Client CLI)
        run: |
          curl -fL -o ijhttp.zip "https://jb.gg/ijhttp/latest"
          unzip -qo ijhttp.zip
          ./ijhttp --version

      - name: Run HTTP tests
        run: ./ijhttp --env-file http-client.env.json --env local --report pollapp.http

      - name: Upload HTTP test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: http-client-report
          path: reports/

      - name: Upload app log (if failed)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: app-log
          path: app.log

      - name: Stop app
        if: always()
        run: |
          if [ -n "${{ env.APP_PID }}" ]; then kill ${{ env.APP_PID }} || true; fi