name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        # caching is handled by the action itself. :contentReference[oaicite:3]{index=3}

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

  http-tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Start app on 8080
        run: |
          nohup ./gradlew bootRun --no-daemon > app.log 2>&1 &
          echo "APP_PID=$!" >> $GITHUB_ENV

      - name: Wait for app (60s)
        run: |
          for i in {1..60}; do
            if curl -sf http://127.0.0.1:8080/ping >/dev/null; then exit 0; fi
            # actuator alternative if present:
            if curl -sf http://127.0.0.1:8080/actuator/health >/dev/null; then exit 0; fi
            sleep 1
          done
          echo "Server didn't start in time"
          tail -n 200 app.log || true
          exit 1
        # Using /actuator/health is the standard readiness probe if actuator is added. :contentReference[oaicite:4]{index=4}

      - name: Install unzip
        run: sudo apt-get update && sudo apt-get install -y unzip

      - name: Download HTTP Client CLI (ijhttp)
        run: |
          curl -fL -o ijhttp.zip "https://jb.gg/ijhttp/latest"
          unzip -qo ijhttp.zip
          ./ijhttp/ijhttp --version

      - name: Run HTTP tests
        run: ./ijhttp/ijhttp scratch.http --env-file http-client.env.json --env local --report
        # ijhttp usage with files + env flags per docs. :contentReference[oaicite:5]{index=5}

      - name: Upload HTTP test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: http-client-report
          path: reports/

      - name: Upload app log on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: app-log
          path: app.log

      - name: Stop app
        if: always()
        run: |
          if [ -n "${{ env.APP_PID }}" ]; then kill ${{ env.APP_PID }} || true; fi
